version: "3"

services:
  node:
    build: ./api
    container_name: express-mongo
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app:z
    restart: on-failure
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      default:
        aliases:
          - dev.api.dashboard.fr
          - localhost
    environment:
      IP_ADRESS: 10.10.250.213
      JWT_KEY: WinterIsComingGOT2019

  # Mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db:z
    environment:
      MONGO_INITDB_DATABASE: mongo

volumes:
  database:
